autocmd Filetype gitcommit setlocal spell textwidth=72
set backspace=2         " backspace in insert mode works like normal editor
syntax on               " syntax highlighting
filetype indent on      " activates indenting for files
set autoindent          " auto indenting
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set number              " line numbers
colorscheme desert      " colorscheme desert
set nobackup            " get rid of anoying ~file
