PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Add homebrew binaries
export PATH="/usr/local/bin:$PATH"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

# Add rbenv
export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"

# export PATH="$HOME/.dotfiles/bin:$HOME/Library/Python/3.7/bin"

# Add go
export PATH="/usr/local/go/bin:$PATH"

# GOAT specific
export GOPRIVATE="github.com/goatapp"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
