PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Add homebrew binaries
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/usr/local/bin:$PATH"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

# Add rbenv
eval "$(rbenv init - --no-rehash zsh)"
export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"

# Add pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

# export PATH="$HOME/.dotfiles/bin:$HOME/Library/Python/3.7/bin"

# Add GOPATH
export PATH="$PATH:/opt/homebrew/opt/go@1.23/bin"
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)
export GOBIN=$GOPATH/bin
