PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Add homebrew binaries
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$PATH:/usr/local/bin"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

# Add rbenv
eval "$(rbenv init - --no-rehash zsh)"
export PATH="$PATH:$HOME/.rbenv/shims:$HOME/.rbenv/bin"

# Add pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PATH:$PYENV_ROOT/bin"

# export PATH="$HOME/.dotfiles/bin:$HOME/Library/Python/3.7/bin"

# Add GOPATH
export GOROOT=$(/opt/homebrew/bin/go env GOROOT)
export PATH="$PATH:$GOROOT/bin"
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)
export GOBIN=$GOPATH/bin

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# mysql
export PATH="/opt/homebrew/opt/mysql@8.4/bin:$PATH"

# psql
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

# java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# python
export PATH="/Users/paulyeo/.local/bin:$PATH"
