PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
export MYSQL_PATH=/usr/local/Cellar/mysql/5.7.17
export PATH="/Users/paulyeo/.rbenv/shims:/Users/paulyeo/.rbenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin:/Users/paulyeo/bin:$MYSQL_PATH/bin:/Users/paulyeo/miniconda3/bin"
export PS1='%n@%1~$ '

# zsh settings
autoload -U compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

if [ -z "$HISTFILE" ]; then
  HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=SAVEHIST=10000
setopt inc_append_history
setopt sharehistory
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space

alias ls="ls -FG"
alias ll="ls -l"
alias be="bundle exec"
alias tls="tmux list-session"
alias topen="tmux attach -t"
alias tnew="tmux new -s"
alias td="tmux detach"

for zsh_source in $HOME/.dotfiles/zsh/config/*.zsh; do
	source $zsh_source
done

source ~/.dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# ensure_tmux_is_running
