for zsh_source in $HOME/.dotfiles/zsh/config/*.zsh; do
	source $zsh_source
done

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# ensure_tmux_is_running

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
