#!/bin/sh

protected_branch='mainline'

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch = $protected_branch ]; then
  echo "Never push to '$protected_branch'"
  exit 1
fi

exit 0
